
<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="process.phtml" method="post">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="surname">lastname:</label> 
       <input type="surname" id="surname" name="surname" required><br>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br>

    
        <label for="placement">Placement:</label>
        <input type="placement" id="placement" name="placement" required><br> 

        <label for="Institution">Institution:</label>
        <input type="institution" id="institution" name="institution" required><br> 

        <a href = "process"></a>

        =<output name ="name" ></output>


        <?php
        /*
        echo '<form method ="POST" action = "process">
        <input type="submit"/>
        </form>';
        */
        ?>


    </form>
</body>
</html>

<!--
<!DOCTYPE HTML>  
<html>
<head>
  <style>
    .error {color : #f0f0f0}
    </style>
</head>
<body>  

<?php
/*
// define variables and set to empty values
//error variables
$titleErr = $nameErr = $emailErr = $genderErr = $websiteErr = "";
$title = $name = $email = $gender = $comment =  "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
  if (empty($_POST["title"])) {
    $titleErr = "Tittle is required";
  } else {
    $name = test_input($_POST["title"]);
  }

  if (empty($_POST["name"])) {
    $nameErr = "Name is required";
  } else {
    $name = test_input($_POST["name"]);
  }
  
  if (empty($_POST["email"])) {
    $emailErr = "Email is required";
  } else {
    $email = test_input($_POST["email"]);
  }
    

  if (empty($_POST["comment"])) {
    $comment = "";
  } else {
    $comment = test_input($_POST["comment"]);
  }

  if (empty($_POST["gender"])) {
    $genderErr = "Gender is required";
  } else {
    $gender = test_input($_POST["gender"]);
  }
}

function test_input($data) { //function test_input that returns data
  $data = trim($data);
  $data = stripslashes($data);
  $data = htmlspecialchars($data);
  return $data;
}
*/
?>

<h2>PHP Form Validation</h2>
<p><span class="error">* required field</span></p>
<form method="post" action="<?php //echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"> 
Title: <input type="text" name="title">
  <span class="error">* <?php //echo $tittleErr;?></span>
  <br><br>
  Name: <input type="text" name="name">
  <span class="error">* <?php //echo $nameErr;?></span>
  <br><br>
  E-mail: <input type="text" name="email">
  <span class="error">* <?php// echo $emailErr;?></span>
  <br><br>
  Comment: <textarea name="comment" rows="5" cols="40"></textarea>
  <br><br>
  Gender:
  <input type="radio" name="gender" value="female">Female
  <input type="radio" name="gender" value="male">Male
  <input type="radio" name="gender" value="other">Other
  <span class="error">* <?php //echo $genderErr;?></span>
  <br><br>
  <input type="submit" name="submit" value="Submit">  
</form>

<?php
/*
echo "<h2>Your Input:</h2>";
echo $title;
echo "<br>";
echo $name;
echo "<br>";
echo $email;
echo "<br>";
echo $comment;
echo "<br>";
echo $gender;
?>
*/


