
<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="process" method="POST">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="surname">lastname:</label> 
       <input type="surname" id="surname" name="surname" required><br>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br>

    
        <label for="placement">Placement:</label>
        <input type="placement" id="placement" name="placement" required><br> 

        <label for="Institution">Institution:</label>
        <input type="institution" id="institution" name="institution" required><br> 

   
    </form>
</body>
</html>

<?php
        
        echo '<form method ="POST" action = "process">
        <input type="submit"/>
        </form>';
    
        if ($_SERVER[ 'REQUEST_METHOD'] === 'GET')
      {
        echo "Name :".$user -> get_name() ."<br>"; 
        echo "Surname :".$user -> get_surname() ."<br>"; 
        echo "Email:".$user -> get_email() ."<br>"; 
        echo "Placement :".$user -> get_placement() ."<br>"; 
        echo "Institution :".$user -> get_institution() ."<br>"; 


      }


        ?>
