<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="process.php" method="post">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="surname">lastname:</label> 
       <input type="surname" id="surname" name="surname" required><br>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br>

    
        <label for="placement">Placement:</label>
        <input type="placement" id="placement" name="placement" required><br> 

        <label for="Institution">Institution:</label>
        <input type="institution" id="institution" name="institution" required><br> 

        <input type="submit" value="Submit">
    </form>
</body>
</html>